apiVersion: v1
kind: Service
metadata:
  name: api-star-wars-service
spec:
  type: ClusterIP
  selector:
    app: api-star-wars
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      #nodePort: 30007