apiVersion: v1
kind: ConfigMap
metadata:
  name: api-star-wars-config
data:
  # property-like keys; each key maps to a simple value
  port: "8080"
  config_file: "/config/api-star-wars.yaml"
  #
  # file-like keys
  hello-api.yaml: |
    message: Olá amiguinho, agora são %s!
    time_layout: "15:04"